# This is the PROD docker compose file, which launches both front and back end.
services:
  frontend:
    image: mvlancellotti/tennis-frontend:prod
    container_name: tennis-frontend-container
    restart: always
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    ports:
      - 5001:80
  backend:
    image: mvlancellotti/tennis-backend:prod
    container_name: tennis-backend-container
    restart: always
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    ports:
      - 5000:80
